title: "e.g., geOrchestra 25.0.3, Gateway 2.0.1"
body:
  - type: dropdown
    id: type_of_release
    attributes:
      label: Release Type
      options:
        - Stable
        - Pre-release
      default: 0
    validations:
      required: true

  - type: textarea
    id: release_summary
    attributes:
      label: Summary
      description: "Remove unnecessary information."
      value: |
        #### 🚀 New Features & Configuration

        #### 🛠 Improvements & Cleanup

        #### 🐛 Bugfixes
  
    validations:
      required: false

  - type: input
    id: changelog_link
    attributes:
      label: 🔗 Release Link
      description: "Link to the this release"
      placeholder: "https://github.com/georchestra/geoserver/releases/tag/2.27.4-georchestra-02"
    validations:
      required: true
