title: "e.g., geOrchestra 25.0.3, Gateway 2.0.1"
body:
  - type: markdown
    attributes:
      value: |
        ## Release Information
        Fill out the sections below. **If a section is not applicable, you can leave it blank.**

  - type: textarea
    id: new_features
    attributes:
      label: 🚀 New Features & Configuration
    validations:
      required: false

  - type: textarea
    id: improvements
    attributes:
      label: 🛠 Improvements & Cleanup
      placeholder: "List improvements or dependency updates..."
    validations:
      required: false

  - type: textarea
    id: bugfixes
    attributes:
      label: 🐛 Bugfixes
      placeholder: "Fixed #4618, etc."
    validations:
      required: false

  - type: markdown
    attributes:
      value: "---"
  - type: input
    id: changelog_link
    attributes:
      label: 🔗 Full Changelog Link
      description: "Link to the full changelog for this release (e.g., GitHub Release page)"
      placeholder: "https://github.com/georchestra/geoserver/releases/tag/2.27.4-georchestra-02"
    validations:
      required: true
