title: "e.g., geOrchestra 25.0.3, Gateway 2.0.1"
body:
  - type: markdown
    attributes:
      value: |
        ## Release Information
        Fill out the sections below. **If a section is not applicable, you can leave it blank.**

  - type: textarea
    id: release_summary
    attributes:
      label: Summary
      value: |
        ### 🚀 New Features & Configuration

        ### 🛠 Improvements & Cleanup

        ### 🐛 Bugfixes
  
    validations:
      required: false

  - type: input
    id: changelog_link
    attributes:
      label: 🔗 Full Changelog Link
      description: "Link to the full changelog for this release (e.g., GitHub Release page)"
      placeholder: "https://github.com/georchestra/geoserver/releases/tag/2.27.4-georchestra-02"
    validations:
      required: true
